# Generated by Django 5.0 on 2023-12-17 16:28

import django.db.models.deletion
import stud_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField(verbose_name='Студент')),
                ('student_course', models.TextField(verbose_name='Курс студента')),
                ('student_group', models.TextField(verbose_name='Группа студента')),
            ],
            options={
                'verbose_name': 'Информация о студенте',
                'verbose_name_plural': 'Информация о студентах',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.TextField(verbose_name='Преподаватель')),
                ('teacher_kaf', models.TextField(verbose_name='Кафедра преподавателя')),
                ('teacher_subject', models.TextField(verbose_name='Предмет преподавателя')),
            ],
            options={
                'verbose_name': 'Информация о преподавателе',
                'verbose_name_plural': 'Информация о преподавателях',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('mark', models.IntegerField(validators=[stud_app.models.mark_validator], verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Успеваемость студента',
                'verbose_name_plural': 'Успеваемость студентов',
                'db_table': 'performance',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('indicator', models.BooleanField(verbose_name='Посещение')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Посещения студента',
                'verbose_name_plural': 'Посещения студентов',
                'db_table': 'attendance',
            },
        ),
    ]
